AllCops:
  TargetRubyVersion: 2.4.1

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

# Disable class documentation.
Style/Documentation:
  Enabled: false

# Disable parallel assignment restriction.
Style/ParallelAssignment:
  Enabled: false

# Exclude Style/ClassVars Cop for Framework class.
Style/ClassVars:
  Enabled: true
  Exclude:
    - lib/framework.rb
